name: Build and Deploy sanny to Hetzner (test-environment)
on:
  push:
    branches:
      - test
    paths:
      - 'sanny/**'
      - 'shared/packages/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Copy favicon from root
        run: cp ./favicon.ico ./sanny/public/

      - name: Lint the projects
        run: npm run lint:sanny ; npm run lint:shared

      - name: Build shared packages
        run: npm run build:shared

      - name: Build the project
        run: npm run build:sanny

  deploy:
    needs: lint-and-build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Hetzner via FTP (test)
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          security: loose
          local-dir: ./sanny/dist/
          server-dir: /public_html/dev/